### ISSUE TITLE
reproduction about BART-FT

### ISSUE THREAD

**Issue by elevenofji** [HLTCHKUST/QFS#2]
Hi, I just change some codes to reproduce the results of BART-FT(only finetune the bart for debatepedia, without answer_relevance_score).  I delete all the "s" "eos" tokens in train, val and test dataset，
![image](https://user-images.githubusercontent.com/32663690/143038284-c8091ac7-7e7d-4a37-a5c8-12d9607fe83d.png)
 and add the [CLS] & [SEP] between doc and query. Is there anything wrong? Cause I got weird results in the final "metrics.json".
![image](https://user-images.githubusercontent.com/32663690/143037831-4e84f860-c7cc-4660-8cea-935c9db04843.png)
all the rouge scores are very weird.

**Comment by Iamfinethanksu** [comment]
hi, I have replied your email. hope it help~

For bart fine-tuning, we fine-tune the model on XSUM data first(mentioned in the paper somewhere), then on debatepedia.
